#ROCK
classic_rock = ["The Beatles","The Rolling Stones","Led Zeppelin","Pink Floyd","The Who","Queen","The Doors","Creedence Clearwater Revival","Lynyrd Skynyrd","Eagles","Fleetwood Mac","Boston","Journey","Foreigner","Kansas","Supertramp","Chicago","The Kinks","Jethro Tull","The Beach Boys","Bob Dylan","Neil Young","Eric Clapton","Cream","Jefferson Airplane","Grateful Dead","The Velvet Underground","Deep Purple","The Animals","The Hollies","The Zombies","Van Morrison","Elton John","David Bowie","Santana","Steppenwolf","ZZ Top","The Byrds","T. Rex","Bad Company","Ten Years After","Free","The Guess Who","Blue Öyster Cult","Roxy Music","The Doobie Brothers","Heart","REO Speedwagon","Asia","Electric Light Orchestra","The Steve Miller Band","Johnny Cash","Toto","The Mamas & the Papas","The Doors","Survivor"]
hard_rock = ["AC/DC","Aerosmith","Van Halen","Guns N' Roses","Bon Jovi","Def Leppard","Kiss","Scorpions","Whitesnake","Deep Purple","Black Sabbath","Ozzy Osbourne","Dio","Judas Priest","Motörhead","Alice Cooper","Rainbow","Thin Lizzy","UFO","Uriah Heep","Nazareth","Blue Öyster Cult","Ted Nugent","Ratt","Quiet Riot","Skid Row","Mötley Crüe","Twisted Sister","Great White","Tesla","W.A.S.P.","Europe","Bad Company","The Cult","Dokken","Extreme","White Lion","Lita Ford","Slaughter","FireHouse","Y&T","Krokus","April Wine","Blue Cheer","Kingdom Come","MSG (Michael Schenker Group)","Gary Moore","Robin Trower","Budgie","Humble Pie","Free"]
grunge = ["Nirvana","Pearl Jam","Soundgarden","Alice in Chains","Stone Temple Pilots","Mudhoney","Temple of the Dog","Mother Love Bone","Screaming Trees","Melvins","Bush","Silverchair","Candlebox","Green River","Mad Season","Tad","Dinosaur Jr.","Hole","L7","Mondo Generator","Seether","3 Doors Down"]
alternative_rock = ["Radiohead","R.E.M.","Pixies","The Smashing Pumpkins","Foo Fighters","The Cure","Muse","Placebo","Weezer","Interpol","The Strokes","Arctic Monkeys","Blur","Oasis","The Killers","Kings of Leon","The White Stripes","Franz Ferdinand","Bloc Party","Incubus","System of a Down","Nine Inch Nails","Depeche Mode","Jane's Addiction","Sonic Youth","The Verve","Garbage","The National","Paramore","Imagine Dragons","Coldplay"]
punk_rock = ["Ramones","Sex Pistols","The Clash","Dead Kennedys","Bad Religion","NOFX","Green Day","The Offspring","Rancid","Misfits","Black Flag","Social Distortion","Pennywise","Descendents","Buzzcocks","The Damned","The Adicts","The Undertones","Operation Ivy","Anti-Flag","Sum 41","Blink-182","AFI","Millencolin","Lagwagon","The Exploited","Dropkick Murphys","Against Me!","The Vandals","Guttermouth"]
indie_rock = ["Gorillaz","Arctic Monkeys","The Strokes","Franz Ferdinand","Vampire Weekend","Bloc Party","The National","Modest Mouse","The Shins","Foals","Phoenix","Alt-J","Two Door Cinema Club","The Kooks","The Libertines","Yeah Yeah Yeahs","Death Cab for Cutie","Bright Eyes","Belle and Sebastian","The Wombats","Interpol","Florence + The Machine","Tame Impala","MGMT","Passion Pit","Bombay Bicycle Club","Grizzly Bear","Arcade Fire","The xx","Cage The Elephant","Of Monsters and Men","The Postal Service"]
prog_rock = ["Pink Floyd","Genesis","Yes","King Crimson","Rush","Emerson, Lake & Palmer","Jethro Tull","Camel","Gentle Giant","Marillion","Porcupine Tree","Dream Theater","Tool","Riverside","IQ","Spock's Beard","Transatlantic","The Flower Kings","Steven Wilson","Kansas","Supertramp","Alan Parsons Project","Rush","Eloy","Opeth","Porcupine Tree","Pain of Salvation","Liquid Tension Experiment","Asia","Frank Zappa"]
garage_rock = ["The White Stripes","The Hives","The Black Keys","The Stooges","MC5","The Sonics","Ty Segall","Thee Oh Sees","The Raconteurs","Jet","Black Rebel Motorcycle Club","The Vines","The Datsuns","The Kills","The Dead Weather","The Fuzztones","The Horrors","Shocking Blue","The Monks","The Cramps","The 13th Floor Elevators","The Gories","The Oblivians","Thee Headcoats","The Warlocks"]
folk_rock = ["Bob Dylan","Neil Young","Simon & Garfunkel","The Byrds","Crosby, Stills, Nash & Young","Cat Stevens","The Band","America","Fleet Foxes","Mumford & Sons","The Lumineers","Of Monsters and Men","Bon Iver","The Avett Brothers","First Aid Kit","The Decemberists","José González","The Waterboys","Passenger","Sufjan Stevens","Iron & Wine","Nick Drake","Bright Eyes","Andrew Bird","Damien Rice","Ben Howard","The Head and the Heart","Lord Huron","Dawes","The Paper Kites"]

#POP
pop_rock = ["Coldplay","Maroon 5","OneRepublic","Imagine Dragons","Train","The Script","Keane","Snow Patrol","The Fray","Goo Goo Dolls","Matchbox Twenty","Nickelback","Lifehouse","Simple Plan","Panic! At The Disco","Fall Out Boy","Paramore","The Killers","Kings of Leon","5 Seconds of Summer","American Authors","Walk the Moon","The Calling","Fun.","Plain White T's","Shinedown","Hinder","Daughtry","Switchfoot","Weezer","U2","All-American Rejects","Twenty One Pilots","Hozier","Shawn Mendes","John Mayer","Ed Sheeran"]
dance_pop = ["Madonna","Britney Spears","Katy Perry","Lady Gaga","Rihanna","Beyoncé","Shakira","Dua Lipa","Justin Timberlake","Christina Aguilera","Ariana Grande","Sia","Avril Lavigne","Miley Cyrus","Jessie J","Bruno Mars","The Weeknd","Usher","Jason Derulo","Pitbull","David Guetta","Calvin Harris","Avicii","Zedd","Maroon 5","Charlie Puth","Selena Gomez","Camila Cabello","Demi Lovato","Nicki Minaj","Black Eyed Peas"]
electropop = ["Lady Gaga","Lorde","Grimes","CHVRCHES","Robyn","MØ","Halsey","Ellie Goulding","AlunaGeorge","Charli XCX","Tove Lo","FKA twigs","Billie Eilish","The Weeknd","Owl City","Passion Pit","MGMT","Foster the People","La Roux","Kesha","Marina","Years & Years","Zara Larsson","Alessia Cara","Dua Lipa","Bebe Rexha","Troye Sivan","Rina Sawayama","BANKS","Aurora","Florence + The Machine"]
latin_pop = ["Shakira","Bad Bunny","J Balvin","Daddy Yankee","Enrique Iglesias","Ricky Martin","Maluma","Ozuna","Becky G","Karol G","Rosalía","Luis Fonsi","Nicky Jam","Anitta","Marc Anthony","Jennifer Lopez","Don Omar","Romeo Santos","Camila Cabello","CNCO","Sebastián Yatra","Maná","Luis Miguel","Gloria Estefan","Carlos Vives","Gente de Zona","Farruko","Wisin & Yandel","Pedro Capó","Feid","Myke Towers"]
rnb_pop = ["Michael Jackson","Prince","Usher","Chris Brown","R. Kelly","Bruno Mars","The Weeknd","Alicia Keys","Mariah Carey","Whitney Houston","Beyoncé","Rihanna","Frank Ocean","SZA","TLC","Destiny's Child","Trey Songz","Ne-Yo","Jason Derulo","Akon","Ne-Yo","Mary J. Blige","Janet Jackson","Jhené Aiko","Miguel","Ty Dolla $ign","Giveon","Daniel Caesar","H.E.R.","Summer Walker","Kehlani"]
teen_pop = ["Britney Spears","NSYNC","Backstreet Boys","Justin Bieber","Miley Cyrus","Selena Gomez","Demi Lovato","Ariana Grande","Shawn Mendes","Zayn","Harry Styles","Louis Tomlinson","Niall Horan","One Direction","Jonas Brothers","Taylor Swift","Billie Eilish","Olivia Rodrigo","Liam Payne","Camila Cabello","Charlie Puth","5 Seconds of Summer","Hannah Montana","Rebecca Black","Zara Larsson","Dove Cameron","Sabrina Carpenter","Noah Cyrus","JoJo Siwa","Fifth Harmony","Little Mix"]
synthpop = ["Depeche Mode","Pet Shop Boys","New Order","A-ha","Tears for Fears","Eurythmics","Duran Duran","Soft Cell","The Human League","Erasure","OMD","Yazoo","Howard Jones","Spandau Ballet","Kraftwerk","Visage","Blancmange","Alphaville","a-ha","Cut Copy","Hot Chip","Future Islands","M83","The Postal Service","Empire of the Sun","CHVRCHES","Grimes","La Roux","Ladytron","Pet Shop Boys","Robyn"]
#french_pop = ["Daft Punk","Stromae","David Guetta","Zaz","Indochine","Johnny Hallyday","Mylène Farmer","Clara Luciani","Angèle","Louane","Vianney","Slimane","Soprano","Gims","Maître Gims","Orelsan","Nekfeu","Julien Doré","Christophe Maé","Calogero","Étienne Daho","France Gall","Michel Sardou","Joe Dassin","Stéphane Eicher","Aya Nakamura","Amir","Jul","Bigflo & Oli","Patrick Bruel","Renaud"]

#RAP
old_school_hip_hop = ["2Pac","The Notorious B.I.G.","Dr. Dre","Snoop Dogg","N.W.A","Ice Cube","Eazy-E","Public Enemy","Run-D.M.C.","LL Cool J","Nas","Jay-Z","A Tribe Called Quest","De La Soul","Wu-Tang Clan","Beastie Boys","KRS-One","Eric B. & Rakim","Ice-T","Big Daddy Kane","Boogie Down Productions","Outkast","Scarface","The Pharcyde","Mobb Deep"]
ninety_s_hip_hop = ["Nas","Jay-Z","2Pac","The Notorious B.I.G.","Wu-Tang Clan","Mobb Deep","Dr. Dre","Snoop Dogg","DMX","Missy Elliott","Eminem","Lauryn Hill","Outkast","The Fugees","Busta Rhymes","Ice Cube","Bone Thugs-n-Harmony","Ludacris","Xzibit","Redman","Method Man","De La Soul","Common","Q-Tip","The Roots"]
two_thousand_hip_hop = ["Eminem","50 Cent","Kanye West","Lil Wayne","T.I.","Rick Ross","Nas","Jay-Z","Snoop Dogg","Pusha T","Kid Cudi","Drake","Nicki Minaj","J. Cole","Big Sean","Wiz Khalifa","B.o.B","Ludacris","Flo Rida","Pitbull","T-Pain","Young Jeezy","Game","Lupe Fiasco","Macklemore"]
trap = ["Future","Young Thug","Travis Scott","Lil Baby","Gunna","21 Savage","Migos","Playboi Carti","A$AP Rocky","A$AP Ferg","Lil Uzi Vert","Chief Keef","Kodak Black","DaBaby","Polo G","Lil Durk","Roddy Ricch","Moneybagg Yo","Quavo","Offset","Metro Boomin","Juice WRLD","Pop Smoke","NAV","Don Toliver"]
drill = ["Chief Keef","Lil Durk","Polo G","King Von","Fivio Foreign","Pop Smoke","Lil Reese","G Herbo","Sheff G","Sleepy Hallow","Central Cee","Headie One","Dave","Russ Millions","Digga D","Loski","Abra Cadabra","Lil Mabu","Tee Grizzley","42 Dugg"]
conscious_rap = ["Kendrick Lamar","J. Cole","Common","Mos Def","Talib Kweli","Lauryn Hill","Lupe Fiasco","A Tribe Called Quest","The Roots","Immortal Technique","Brother Ali","KRS-One","Rapsody","Logic","Mac Miller","NF","Anderson .Paak","Chance the Rapper","Denzel Curry","Noname","Black Thought","Sa-Roc","Erykah Badu"]
pop_rap = ["Drake","Post Malone","Nicki Minaj","Cardi B","Travis Scott","Lil Nas X","Doja Cat","Megan Thee Stallion","Tyga","Iggy Azalea","Akon","Flo Rida","Pitbull","Black Eyed Peas","LMFAO","Saweetie","Latto","Jack Harlow","Machine Gun Kelly","The Weeknd","Swae Lee","Ty Dolla $ign","French Montana"]
fr_rap = ["Nekfeu","Orelsan","PNL","Damso","SCH","Booba","Kaaris","Jul","Ninho","Freeze Corleone","Gims","Soprano","Lomepal","Vald","Bigflo & Oli","Laylow","PLK","Maes","Rilès","Roméo Elvis","Hamza","Josman","Fianso","Niska","Alpha Wann","Lacrim","MHD","Koba LaD","Heuss l'Enfoiré","Tiakola"]
uk_rap = ["Stormzy","Dave","Central Cee","Skepta","Giggs","AJ Tracey","Headie One","J Hus","Slowthai","Dave East","Wretch 32","Loyle Carner","Little Simz","Fred again..","Kano","Bugzy Malone","Dave (UK)","Chip","Dizzee Rascal","M Huncho","Knucks","Nines","Unknown T"]

#Chanson française
chanson_fr_classique = ["Édith Piaf","Jacques Brel","Georges Brassens","Charles Aznavour","Serge Gainsbourg","Françoise Hardy","Jacques Dutronc","Léo Ferré","Claude François","Johnny Hallyday","Dalida","Gilbert Bécaud","Serge Lama","Joe Dassin","Michel Polnareff","France Gall","Michel Sardou","Nino Ferrer","Renaud","Daniel Balavoine","Alain Souchon","Laurent Voulzy","Pierre Bachelet","Yves Montand","Barbara","Juliette Gréco","Charles Trenet","Henri Salvador","Richard Anthony","Sheila"]
chanson_fr_annees_60_70 = ["Claude François","Johnny Hallyday","Serge Gainsbourg","France Gall","Michel Polnareff","Joe Dassin","Michel Sardou","Jacques Dutronc","Françoise Hardy","Nino Ferrer","Eddy Mitchell","Ringo","Stone et Charden","Michel Delpech","Georges Moustaki","Christophe","Hugues Aufray","Sheila","Cloclo","Les Compagnons de la Chanson","Dalida","Adamo","Richard Anthony","Salvatore Adamo","Georges Brassens","Jacques Brel","Léo Ferré"]
chanson_fr_annees_80_90 = ["Daniel Balavoine","Jean-Jacques Goldman","Renaud","Alain Bashung","Indochine","Mylène Farmer","Étienne Daho","Francis Cabrel","Céline Dion","Elsa","Images","Téléphone","Noir Désir","Roch Voisine","Patrick Bruel","Florent Pagny","Axel Bauer","Éric Serra","Kyo","Sardou","Gold","Emile & Images","Début de Soirée","Partenaire Particulier"]
variete_pop_fr = ["Zaz","Clara Luciani","Angèle","Louane","Vianney","Slimane","Christophe Maé","Calogero","Amir","Stromae","Gims","Maître Gims","Nolwenn Leroy","Patrick Fiori","Hoshi","Benabar","Raphaël","Cœur de Pirate","Julien Doré","Bigflo & Oli","Orelsan","Soprano","M. Pokora","Jenifer","Tal","Shy'm","Amel Bent","Black M","Kendji Girac","Vitaa"]
chanson_fr_indie = ["Indochine","Air","Phoenix","Daft Punk","Caravan Palace","Christine and the Queens","La Femme","Feu! Chatterton","Pomme","Orelsan","Nekfeu","Lomepal","Vald","Feu! Chatterton","Shaka Ponk","Fishbach","Vendredi sur Mer","Thérapie TAXI","Feist (FR scene overlap)","BB Brunes","Hippocampe Fou","Stupeflip","M83","Woodkid","Dominique A"]
chanson_fr_rap = ["Ninho","PNL","Booba","Kaaris","SCH","Damso","Nekfeu","Orelsan","Jul","Niska","Gazo","Freeze Corleone","Lacrim","Maes","PLK","Koba LaD","Heuss l'Enfoiré","Tiakola","Vald","Laylow","Alpha Wann","Josman","Lomepal","Sofiane","Fianso","RK","SDM","Gradur","Bigflo & Oli","Roméo Elvis"]
chanson_fr_rap_crossover = ["Stromae","Gims","Soprano","Orelsan","Bigflo & Oli","Lomepal","Nekfeu","Vald","PLK","SCH","Damso","Laylow","Jul","Maes","Ninho","Kendji Girac","Black M","M. Pokora","Amir","Vianney","Angèle","Clara Luciani","Christine and the Queens","Louane","Shy'm","Vitaa","Dadju","Franglish","Keen'V","Soolking"]
chanson_fr_electro_pop = ["Daft Punk","David Guetta","Justice","Air","M83","Kavinsky","Stromae","The Avener","Madeon","DJ Snake","Ofenbach","Martin Solveig","Bob Sinclar","Vitalic","Caravan Palace","Breakbot","Yelle","CHAPELIER FOU","Superbus","Bon Entendeur","Woodkid","Rone","Fakear","Synapson","The Blaze","FKJ"]

#ELECTRO

house = ["Daft Punk","David Guetta","Martin Solveig","Bob Sinclar","Kungs","Purple Disco Machine","Armand Van Helden","Frankie Knuckles","Masters At Work","Armin van Buuren","Eric Prydz","Fedde Le Grand","Axwell","Steve Angello","Sebastian Ingrosso","Swedish House Mafia","Solomun","Claptone","Peggy Gou","Disclosure","Calvin Harris","Fisher","John Summit","MK","Gorgon City","Duke Dumont","Tchami","Oliver Heldens","Don Diablo","CamelPhat"]
techno = ["Charlotte de Witte","Amelie Lens","Carl Cox","Adam Beyer","Richie Hawtin","Jeff Mills","Chris Liebing","Paul Kalkbrenner","Tale Of Us","Nina Kraviz","ANNA","Enrico Sangiuliano","Charlotte de Witte","Dax J","Amelie Lens","Alignment","I Hate Models","Reinier Zonneveld","Amelie Lens","Charlotte de Witte","Len Faki","Ben Klock","Kobosil","999999999","Charlotte de Witte","Amelie Lens","Charlotte de Witte","Charlotte de Witte"]
trance = ["Armin van Buuren","Tiesto","Paul van Dyk","Ferry Corsten","ATB","Gareth Emery","Above & Beyond","Andrew Rayel","Vini Vici","Dash Berlin","Aly & Fila","Rank 1","BT","OceanLab","Super8 & Tab","KhoMha","W&W","Marlo","MaRLo","Giuseppe Ottaviani","Ferry Corsten","Cosmic Gate","York","John O'Callaghan","Richard Durand"]
dubstep = ["Sullivan King","Skrillex","Excision","Zomboy","Virtual Riot","Flux Pavilion","Knife Party","Rusko","Borgore","Caspa","Datsik","Barely Alive","Excision","Subtronics","Svdden Death","Slander","ILLENIUM","Marshmello","Seven Lions","Ghastly","Eptic","Crankdat","Pegboard Nerds","FuntCase","Kill The Noise","Kompany"]
drum_and_bass = ["Pendulum","Noisia","Andy C","Sub Focus","Chase & Status","Sigma","Wilkinson","Netsky","Dimension","Goldie","Rudimental","Camo & Krooked","High Contrast","Logistics","London Elektricity","Shapeshifter","S.P.Y","Benny L","Kanine","Friction","Break","DJ Marky","Metrik","Koven","Alix Perez"]
electro_house = ["Skrillex","Zedd","Deadmau5","Porter Robinson","Madeon","Afrojack","Hardwell","Steve Aoki","Diplo","Alesso","KSHMR","W&W","DVBBS","R3HAB","Blasterjaxx","Benny Benassi","Tiësto","Nicky Romero","Ummet Ozcan","Dillon Francis","Cash Cash","Yellow Claw","Carnage","Laidback Luke","Brooks"]
deep_house = ["Disclosure","Lane 8","Ben Böhmer","Jody Wisternoff","Yotto","ARTBAT","Claptone","Solomun","Purple Disco Machine","Moon Boots","Gorgon City","Kölsch","Nick Murphy","Ben Pearce","Matoma","Kygo","Duke Dumont","Lost Frequencies","Robin Schulz","Sam Feldt","Felix Jaehn","Alle Farben","Bakermat","Elderbrook","WhoMadeWho"]
progressive_house = ["Eric Prydz","Deadmau5","Tiësto","Armin van Buuren","Above & Beyond","Swedish House Mafia","Avicii","Calvin Harris","Alesso","Sebastian Ingrosso","Axwell","Nicky Romero","Audien","Ferry Corsten","Paul van Dyk","ATB","Kaskade","Andrew Bayer","Maor Levi","Genix","Jason Ross","Ilan Bluestone","Grum","Sunny Lax","PROFF"]
future_bass = ["Marshmello","Flume","ILLENIUM","San Holo","Porter Robinson","RL Grime","Louis The Child","Said The Sky","Odesza","Owl City","Dabin","SLANDER","Seven Lions","Kaivon","Kasbo","San Holo","Jai Wolf","Lido","Odesza","Flume","Virtual Riot","Wavedash","What So Not","Mura Masa","Droeloe"]
electro_pop = ["Lady Gaga","Dua Lipa","The Weeknd","Billie Eilish","Grimes","Charli XCX","Sia","Rihanna","Ariana Grande","Zedd","Calvin Harris","David Guetta","Avicii","Clean Bandit","MØ","Ellie Goulding","Lorde","Halsey","Troye Sivan","CHVRCHES","Years & Years","FKA twigs","Tove Lo","Robyn","Kesha"]

#METAL

heavy_metal = ["Black Sabbath","Iron Maiden","Judas Priest","Motörhead","Dio","Ozzy Osbourne","Deep Purple","Rainbow","Accept","Saxon","Scorpions","Thin Lizzy","Uriah Heep","UFO","Budgie","Angel Witch","Diamond Head","Manowar","Twisted Sister","W.A.S.P.","Quiet Riot","Def Leppard","Blue Öyster Cult","Krokus","Y&T","Riot","Girlschool","Praying Mantis","Armored Saint","Great White"]
thrash_metal = ["Metallica","Slayer","Megadeth","Anthrax","Exodus","Testament","Overkill","Kreator","Sodom","Death Angel","Destruction","Sepultura","Machine Head","Vio-lence","Havok","Municipal Waste","Coroner","Forbidden","Dark Angel","Artillery","Nuclear Assault","Whiplash","Sacred Reich","Gama Bomb","Evile"]
death_metal = ["Death","Cannibal Corpse","Morbid Angel","Obituary","Deicide","Carcass","Entombed","Dismember","At the Gates","In Flames","Dark Tranquillity","Amon Amarth","Behemoth","Napalm Death","Bloodbath","Bolt Thrower","Autopsy","Nile","Suffocation","Immolation","Hypocrisy","Arch Enemy","Dying Fetus","Gojira","Necrophagist"]
black_metal = ["Mayhem","Burzum","Darkthrone","Emperor","Immortal","Gorgoroth","Satyricon","Cradle of Filth","Dimmu Borgir","Enslaved","Bathory","Watain","Marduk","1349","Xasthur","Abbath","Dissection","Summoning","Drudkh","Uada","Beherit","Dark Funeral","Belphegor","Carpathian Forest","Taake"]
power_metal = ["Helloween","Blind Guardian","Gamma Ray","Sabaton","DragonForce","Rhapsody of Fire","Stratovarius","Avantasia","Kamelot","Nightwish","Sonata Arctica","Edguy","Manowar","Firewind","HammerFall","Battle Beast","Orden Ogan","Powerwolf","Symphony X","Angra","Primal Fear","Falconer","Warkings","Visions of Atlantis","Freedom Call"]
doom_metal = ["Black Sabbath","Candlemass","Electric Wizard","My Dying Bride","Saint Vitus","Type O Negative","Pentagram","Trouble","Paradise Lost","Katatonia","YOB","Solitude Aeturnus","Sunn O)))","Windhand","Acid King","Bell Witch","Pallbearer","Warning","Shape of Despair","Evoken","Thergothon","Esoteric","Anathema","Church of Misery"]
metalcore = ["Killswitch Engage","As I Lay Dying","Bullet for My Valentine","Parkway Drive","Trivium","August Burns Red","Bring Me The Horizon","Architects","A Day To Remember","All That Remains","Shadows Fall","Unearth","Hatebreed","Fit For A King","Memphis May Fire","We Came As Romans","Motionless In White","Of Mice & Men","Northlane","While She Sleeps","Bury Tomorrow","Invent Animate","Polaris","Erra","The Devil Wears Prada"]
nu_metal = ["Korn","Slipknot","Linkin Park","System of a Down","Limp Bizkit","Deftones","Disturbed","Papa Roach","P.O.D.","Godsmack","Mudvayne","Static-X","Coal Chamber","Sevendust","Kittie","Ill Niño","Drowning Pool","Powerman 5000","Taproot","Adema","Breaking Benjamin","Three Days Grace","Skindred","Rob Zombie","Hed PE"]
groove_metal = ["Pantera","Lamb of God","Machine Head","Sepultura","DevilDriver","Exhorder","Chimaira","Soulfly","Gojira","Mastodon","Fear Factory","Prong","White Zombie","High On Fire","Kvelertak","Orange Goblin","Black Label Society","Hellyeah","Five Finger Death Punch","Ill Nino","Crowbar","Down","Corrosion of Conformity","Hatebreed"]
progressive_metal = ["Dream Theater","Opeth","Tool","Queensrÿche","Fates Warning","Symphony X","Between the Buried and Me","Porcupine Tree","Pain of Salvation","Leprous","Periphery","TesseracT","Animals as Leaders","Meshuggah","Steven Wilson","Riverside","Karnivool","Soilwork","Voivod","Haken","Caligula's Horse","The Contortionist","Gojira","Mastodon","Alcest"]